const EErrors = {
  CART_NOT_FOUND: 1,
  PRODUCT_NOT_FOUND: 2,
  PRODUCT_NOT_AVAILABLE: 3,
  STOCK_NOT_AVAILABLE: 4,
  PRODUCT_ALREADY_EXISTS: 5,
  PRODUCT_NOT_EXISTS: 6,
  USER_NOT_EXISTS: 7,
  PASSWORD_NOT_VALID: 8,
  NOT_AUTOHORIZED: 9,
  NOT_PRODUCTS_TICKET: 10,
  USER_NOT_VERIFIED: 11,
  USER_NOT_AUTHORIZED: 12,
  NOT_BUY_OWN_PRODUCTS: 13,
};
export default EErrors;
